#!/bin/sh
/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t sysfs sysfs /sys
/bin/mount -t proc proc /proc

hostname flasher

exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console
exec /sbin/init "$@"
